[package]
name = "chm92"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[dependencies]
rand = "0.6.4"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "state_lookup"
harness = false
